### ISSUE TITLE
Delete this

### ISSUE THREAD

**Issue by kkirigaya** [VelvetThePanda/BatSharp#1]
Please delete this repo as it brings me great sadness to know that something as horrid as this may exist even as a concept. Thanks, management.

**Comment by telugu-boy** [comment]
Please delete this repo as it brings me great sadness to know that something as horrid as this may exist even as a concept. Thanks, management.

**Comment by VelvetThePanda** [comment]
No. 😄

**Comment by Sardonyx78** [comment]
Please delete this repo as it brings me great sadness to know that something as horrid as this may exist even as a concept. Thanks, management.
